### ISSUE TITLE
the API return 404 (or 501/302 when using /api/index.php?)

### ISSUE THREAD

**Issue by Nono-m0le** [FOGProject/fogproject#263]
Hi there,

I'm currently unable to use the API as I constantly got either a 404 or 501/302 (using for instance, this command) : 
`$ curl -H "fog-api-token: MjUwYjkxNGU4YTJkNjM3MDliNmVlZDFjZGE5YjcwNjg2N2Y1ZWE1NjMxMzFkZTk4Y2ZhOWZjNGJjZDUyZGIxNTljODg0NDhiM2RlODBmMzc5ZWFkMTkxxxxx1NDU5OTZhMzIwODJmYThiNWI0MzhhYjkwMDZhNzQ1MTFiNjg" -H  "fog-user-token: NTQ5MWJiMjgxNmI5OTcyZDM5OTMzMWJlZjlkZWM4Y2M2MDg0ZTI5MTQ5MGZlYzdkNmYzY2NjNTc1OGE1ZGE3ODY4NDlkOWU4NjFiMzdmOTU5MDxxxN2NjNDQxYjhlMWI3MjYxZDMxZmRkZmNkY2M1Mjk4ZGNmZGUzMzNiNWY" -X GET http://192.168.6.128/fog/system/info
`
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /fog/system/info was not found on this server.</p>
<hr>
<address>Apache/2.4.34 (Ubuntu) Server at 192.168.6.128 Port 80</address>
</body></html>
```

from apache "acces.log" ; `"GET /fog/system/info HTTP/1.1" 404 453 "-" "curl/7.58.0"`

Using /api/index.php?system/info gave me a 501 : 
`$ curl -H "fog-api-token: MjUwYjkxNGU4YTJkNjM3MDliNmVlZDFjZGE5YjcwNjg2N2Y1ZWE1NjMxMzFkZTk4Y2ZhOWZjNGJjZDUyZGIxNTljODg0NDhiM2RlODBmMzc5ZWFkMTkxxxxx1NDU5OTZhMzIwODJmYThiNWI0MzhhYjkwMDZhNzQ1MTFiNjg" -H  "fog-user-token: NTQ5MWJiMjgxNmI5OTcyZDM5OTMzMWJlZjlkZWM4Y2M2MDg0ZTI5MTQ5MGZlYzdkNmYzY2NjNTc1OGE1ZGE3ODY4NDlkOWU4NjFiMzdmOTU5MDxxxN2NjNDQxYjhlMWI3MjYxZDMxZmRkZmNkY2M1Mjk4ZGNmZGUzMzNiNWY" -X GET http://192.168.6.128/fog/api/index.php?system/info
`
`"GET /fog/api/index.php?system/info HTTP/1.1" 501 678 "-" "curl/7.58.0"`

FYI; here is my (untouched) /etc/apache2/sites-enabled/001-fog.conf:
```
<VirtualHost *:80>
    <FilesMatch "\.php$">
        SetHandler "proxy:fcgi://127.0.0.1:9000/"
    </FilesMatch>
    KeepAlive Off
    ServerName 192.168.2.1
    DocumentRoot /var/www/
    <Directory /var/www/fog/>
        DirectoryIndex index.php index.html index.htm
    </Directory>
    RewriteEngine On
    RewriteCond %{REQUEST_METHOD} ^(TRACE|TRACK)
    RewriteRule .* - [F]
    RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
    RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-d
    RewriteRule ^/fog/(.*)$ /fog/api/index.php [QSA,L]
</VirtualHost>
```

Could you please let me know what else should I check as there is no logs on /opt/fog/log/* related to the API.

**Comment by Quazz** [comment]
I recommend obscuring your API tokens asap.

**Comment by Nono-m0le** [comment]
Already did it but it's anyway offline so...

**Comment by Nono-m0le** [comment]
The solution was to disable the default apache configuration as stated by @Sebastian-Roth here : https://forums.fogproject.org/topic/12456/the-api-return-404-or-501-302-when-using-api-index-php/6

c/c of the solution : 
```
sudo a2dissite 000-default.conf
sudo service apache2 restart
```

**Comment by Sebastian-Roth** [comment]
At first I thought this might be a general issue. But on a Debian based installation I don't see the same issue. Comparing the config files did not shed a light on this.
Then I thought it might be due to different apache versions (Ubuntu with apache from ondrej repo). But as I have fixed #264 and got to try out the original apache 2.4.29-1ubuntu4.3 package it still shows the same weird behavior.
I'll re-open the case as a reminder to find and fix this properly.

**Comment by Nono-m0le** [comment]
@Sebastian-Roth I can confirm that on a fresh install on ubuntu server 18.04.1 (using cdimage / alternate and NOT the live) with the working branch : I still have to do this to get rid of the error 404. (note : the API is still not responding anything though)

**Comment by Sebastian-Roth** [comment]
@Nono-m0le I am getting closer to solving this. Did some more research and tests and found out why Debian is working out of the box but Ubuntu isn't. The essential problem is that the apache default site config and out added FOG site config overlap. See here:
**Ubuntu:**
```
# apachectl -S
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.2.7. Set the 'ServerName' directive globally to suppress this message
VirtualHost configuration:
*:80                   is a NameVirtualHost
         default server 192.168.2.7 (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost 192.168.2.7 (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost 192.168.2.7 (/etc/apache2/sites-enabled/001-fog.conf:1)
ServerRoot: "/etc/apache2"
...
```
**Debian:**
```
# apachectl -S
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
VirtualHost configuration:
*:80                   is a NameVirtualHost
         default server 127.0.1.1 (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost 127.0.1.1 (/etc/apache2/sites-enabled/000-default.conf:1)
         port 80 namevhost 192.168.2.4 (/etc/apache2/sites-enabled/001-fog.conf:1)
ServerRoot: "/etc/apache2"
...
```
See the difference? Debian seems to route the request through 000-default.conf only when this strange loopback address 127.0.1.1 is used. All requests from external hosts (external IP) are routed through 001-fog.conf.

Now Ubuntu is handling things differently but only because it is missing the Debian-style loopback entry in `/etc/hosts`. So I added this line `127.0.1.1       ubuntuhostname` to `/etc/hosts` on my Ubuntu machine, enabled 000-default.conf, restarted apache service and the API is working again.

**Comment by Sebastian-Roth** [comment]
Ok, I decided to disable the `000-default` site config on Ubuntu/Debian systems within the installer script (2ac7df0). Shouldn't cause much harm and does solve the issue properly.
