### ISSUE TITLE
Field "Host Description" not properly escaped for ipxe if multiline in branch working-1.6

### ISSUE THREAD

**Issue by osiktech** [FOGProject/fogproject#660]
I upgraded to working-1.6 for testing purposes.

I noticed another bug besides #655. It seems the "Host Description" field is not properly handled if the field has line breaks for multiline descriptions.

With modsecurity enabled I debugged what the webserver is sending to client.

```
#!ipxe
set fog-ip pxe.example.com
set fog-webroot fog
set boot-url https://${fog-ip}/${fog-webroot}
set setmacto ${net0/mac}
set hostname myhost
set description Created by FOG Reg on November 6, 2024, 2:05 pm
HP Spectre x360 Convertible 14-ea0355ng (2N2A0EA)
set imageID 4
...
```

Once ipxe fetches and parses the boot.php from the fogserver it fails with `HP: command not found`. When I changed the "Host Description" field to a single line field it works with no problem.

I am no php developer but I suspect the bug is probably in [bootmenu.class](https://github.com/FOGProject/fogproject/blob/working-1.6/packages/web/lib/fog/bootmenu.class.php#L1939) starting at line 1939.

Best

**Comment by mastacontrola** [comment]
Did somebody add custom code? I say this because oh no point are we sending a parameter called "description" in the code, so this is coming from somewhere else.

That said, iPXE is a very low level language. No amount of escaping or anything would fix new lines being introduced. That's what's erroring out. It seems the code is working properly, but the error is literally in the description itself. I don't believe ipxe can accept multiline statements, which is partly why we don't present the description field.

**Comment by osiktech** [comment]
There where code changes between dev-branch and working-1.6 branch. 

I never noticed any problems with multiline host description field when I was still using dev-branch. I am not sure if this `set description` is new introduced in working-1.6 branch. Like I said I am not PHP developer. 

But you are right, I found no hint if there is even an option to escape or wrap newline. Looking at the iPXE script send from the fogserver to the client I am seeing no reuse of the variable `description` in it. Maybe you are right and it could dropped entirely?

For reference I am attaching the full iPXE script sended from the server to client. (I anonymized sensitive parts of the script)

[ipxe_menu.txt](https://github.com/user-attachments/files/17800283/ipxe_menu.txt)

**Comment by mastacontrola** [comment]
I found the issue, and apologies this took so long.

Should be fixed in latest.

**Comment by osiktech** [comment]
Great to hear and many thanks, I will try it later tonight and will provide feedback.

**Comment by osiktech** [comment]
Seems to work fine, but I had to downgrade to fog kernel 1.5.10 for my test machines to be able to boot FOS.

**Comment by darksidemilk** [comment]
@osiktech Did you happen to try the newest 'experimental' kernels before trying the older kernels?

**Comment by osiktech** [comment]
@darksidemilk I did, and actually I am using them. They seem to work fine. At least the amd64 and x86 is working without problems. As for the arm64 one, I am still not able to boot my https://github.com/utmapp/UTM virtualized machine (running on my MacBook Pro M1) it hangs at this stage.

![Image](https://github.com/user-attachments/assets/1224dd36-091d-46a9-bb32-ce660c7ea590)

 I also tried to built my own kernel for arm64 using the [fos](https://github.com/FOGProject/fos) project an kernel 6.12.9 but without luck.

Shall I create an separate issue for that in FOS? 

Best

**Comment by darksidemilk** [comment]
Separate issue in fos would be best

**Comment by osiktech** [comment]
Done. See [FOS 101](https://github.com/FOGProject/fos/issues/101)
