### ISSUE TITLE
The Scheduled Tasks feature is not functioning in version 1.6.0-beta.2167

### ISSUE THREAD

**Issue by swireb** [FOGProject/fogproject#707]
**Describe the bug**
I sincerely appreciate FogProject's work. Version 1.5.10 has been flawless for batch OS deployments!
but during my 1.6.0-beta tests, I encountered issues with the Scheduled Tasks functionality:
1. When scheduling a 1-minute recurring task through both hosts and groups, no entries appeared in the Active Tasks list.
2. The group-deployed tasks additionally exhibited incorrect timing behavior.

**Screenshots**

![Image](https://github.com/user-attachments/assets/aeb04454-87f0-431e-a016-5196d5c1f687)

**Software (please complete the following information):**
 - FOG version [1.6.0-beta.2167]
 - OS: [Rocky Linux 9.5]

**Comment by darksidemilk** [comment]
Did 1-minute recurring tasks work before? 
Have you made sure your timezone is correct in `/etc/php.ini` ?
I don't have any recurring tasks, but I do use scheduled deploy tasks in fog 1.6 on a regular basis without issue.
Is the timezone correct on the server?
When you are in the gui and go to create a scheduled task with a specific date/time, does the default show the correct current time?

I have found there to be a 1-2 minute delay in the tasks starting after the scheduled time passes.
There are also services that fog installed that need to be running, i.e. `sudo systemctl status FOGScheduler.service` to check if the scheduler is running. other Fog services start with all caps `FOG` i.e. 
``` 
sudo systemctl list-units FOG*
  UNIT                        LOAD   ACTIVE SUB     DESCRIPTION
  FOGFileDeleter.service      loaded active running FOGFileDeleter
  FOGImageReplicator.service  loaded active running FOGImageReplicator
  FOGImageSize.service        loaded active running FOGImageSize
  FOGMulticastManager.service loaded active running FOGMulticastManager
  FOGPingHosts.service        loaded active running FOGPingHosts
  FOGScheduler.service        loaded active running FOGScheduler
  FOGSnapinHash.service       loaded active running FOGSnapinHash
  FOGSnapinReplicator.service loaded active running FOGSnapinReplicator
```

You should also check the `/opt/fog/log/fogscheduler.log` for any errors. The timestamps in this log should also match your timezone.

**Comment by swireb** [comment]
Thank you very much for your reply.

I tried to configure the correct timezone for PHP and restarted the server.

 However, after re-deploying the task, the incorrect time is still displayed. 

Below are the results of my checks.




```
[root@localhost ~]# php -i | grep "Default timezone"
Default timezone => Asia/Shanghai

[root@localhost ~]# sudo systemctl status FOGScheduler.service
● FOGScheduler.service - FOGScheduler
     Loaded: loaded (/usr/lib/systemd/system/FOGScheduler.service; enabled; preset: disabled)
     Active: active (running) since Thu 2025-05-22 19:02:12 CST; 7h left
   Main PID: 1070 (php)
      Tasks: 2 (limit: 48712)
     Memory: 13.6M
        CPU: 179ms
     CGroup: /system.slice/FOGScheduler.service
             ├─1070 php /opt/fog/service/FOGTaskScheduler/FOGTaskScheduler
             └─1086 php /opt/fog/service/FOGTaskScheduler/FOGTaskScheduler

May 22 19:02:12 localhost.localdomain systemd[1]: Started FOGScheduler.

[root@localhost ~]# sudo systemctl list-units FOG*
  UNIT                        LOAD   ACTIVE SUB     DESCRIPTION        
  FOGFileDeleter.service      loaded active running FOGFileDeleter
  FOGImageReplicator.service  loaded active running FOGImageReplicator
  FOGImageSize.service        loaded active running FOGImageSize
  FOGMulticastManager.service loaded active running FOGMulticastManager
  FOGPingHosts.service        loaded active running FOGPingHosts
  FOGScheduler.service        loaded active running FOGScheduler
  FOGSnapinHash.service       loaded active running FOGSnapinHash
  FOGSnapinReplicator.service loaded active running FOGSnapinReplicator
LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.
8 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.


[root@localhost ~]# cat /opt/fog/log/fogscheduler.log
[05-22-25 7:02:12 pm] 
==================================
===        ====    =====      ====
===  =========  ==  ===   ==   ===
===  ========  ====  ==  ====  ===
===  ========  ====  ==  =========
===      ====  ====  ==  =========
===  ========  ====  ==  ===   ===
===  ========  ====  ==  ====  ===
===  =========  ==  ===   ==   ===
===  ==========    =====      ====
==================================
===== Free Opensource Ghost ======
==================================
============ Credits =============
= https://fogproject.org/Credits =
==================================
== Released under GPL Version 3 ==
==================================
[05-22-25 7:02:12 pm] Interface Ready with IP Address: 10.0.0.245
[05-22-25 7:02:12 pm] Interface Ready with IP Address: 127.0.0.1
[05-22-25 7:02:12 pm] Interface Ready with IP Address: 127.0.1.1
[05-22-25 7:02:12 pm] Interface Ready with IP Address: localhost.localdomain
[05-22-25 7:02:12 pm]  * Starting TaskScheduler Service
[05-22-25 7:02:12 pm]  * Checking for new items every 60 seconds
[05-22-25 7:02:12 pm]  * Starting service loop
[05-22-25 7:02:12 pm]  * No tasks found!

```
I also tried creating a task that runs every minute

![Image](https://github.com/user-attachments/assets/fae55cfd-6392-4fb8-bb39-b06155dcbe35)

![Image](https://github.com/user-attachments/assets/a0565c98-ab35-4d9a-8092-3c0e03f88b29)

**Comment by darksidemilk** [comment]
The 1970 being the time for the schedule is real odd. Does it work if you specify a time?

**Comment by lukebarone** [comment]
32 bit os?

**Comment by swireb** [comment]
> The 1970 being the time for the schedule is real odd. Does it work if you specify a time?

In addition to noticing that the task time is incorrect, I also found that the task type is wrong. I created it as a scheduled task, but it ended up being categorized as 'Delayed'. I tried manually modifying the time and type directly in the database, but it still didn't work correctly.

**Comment by swireb** [comment]
> 32 bit os?

[root@localhost ~]# uname -m
x86_64

**Comment by darksidemilk** [comment]
I'm pretty sure delayed and scheduled are the same in this context.
If the time in the server is right and the time setting sin fog are right there must be somewhere we have a revert to the "epoch" time of 1970.

**Comment by swireb** [comment]
> I'm pretty sure delayed and scheduled are the same in this context. If the time in the server is right and the time setting sin fog are right there must be somewhere we have a revert to the "epoch" time of 1970.


I created a 1-hour scheduled task for both hosts and groups through the web interface for comparison.

By checking the `scheduledTasks` table in the database, I found that the scheduled task created for groups has incorrect values in the following fields.

![Image](https://github.com/user-attachments/assets/7e68b527-7cfb-4185-8dc6-7d85c344ac14)



I manually corrected the incorrect fields in the database.

![Image](https://github.com/user-attachments/assets/c57dd7e0-5537-4231-8724-2e273c1311ba)


After refreshing the web interface, the scheduled task times are displayed correctly.

![Image](https://github.com/user-attachments/assets/31008629-dd6a-4cfa-8aa2-ea76fd64221c)


While checking the service operation, I found an alert, but I'm not sure whether this alert is the direct cause of the bug.

```
[root@localhost ~]# systemctl status FOGScheduler.service
● FOGScheduler.service - FOGScheduler
     Loaded: loaded (/usr/lib/systemd/system/FOGScheduler.service; enabled; preset: disabled)
     Active: active (running) since Mon 2025-05-26 17:26:56 CST; 6min ago
   Main PID: 1454 (php)
      Tasks: 2 (limit: 22943)
     Memory: 26.2M
        CPU: 24.920s
     CGroup: /system.slice/FOGScheduler.service
             ├─1454 php /opt/fog/service/FOGTaskScheduler/FOGTaskScheduler
             └─1542 php /opt/fog/service/FOGTaskScheduler/FOGTaskScheduler

May 26 17:26:56 localhost.localdomain systemd[1]: Started FOGScheduler.
May 26 17:31:31 localhost.localdomain env[1542]: PHP Warning:  Undefined variable $stat in /var/www/html/fog/lib/fog/group.class.php on line 768
```


Finally, I restarted the server, and the scheduled task created through groups began working normally.

**Comment by darksidemilk** [comment]
I have now been able to recreate this issue with a cron style every minute task. 
Still narrowing it down.

**Comment by darksidemilk** [comment]
<img width="2517" height="308" alt="Image" src="https://github.com/user-attachments/assets/15234820-86ce-4f7a-ae3a-303f635fe7dc" />

```
AH01071: Got error 'PHP message: PHP Warning:  Undefined array key 1 in /var/www/html/fog/lib/fog/fogcron.class.php on line 162; 
```

**Comment by darksidemilk** [comment]
It appears to be scheduled tasks on groups specifically. Cron and delayed tasks on individual hosts work fine, but the date is wrong for group scheduled tasks.

**Comment by darksidemilk** [comment]
@swireb sorry for the delay. I had some time to dig into this.
There were a couple little things that were causing it. Biggest thing was when the given time should have been being set for a delayed or a cron type scheduled task for a group, a variable was being reset.
Basically there was a typo where `=` was there instead of `==` when the scheduled task is being created.

```
 ->set('type', $scheduleType = 'single' ? 'S' : 'C')
```

was always resetting the type given from 'single' or 'cron' to 'S'.
changed this to

```
->set('type', $scheduleType == 'single' ? 'S' : 'C')
```
That value being reset was making it so the statements after to actually set the cron fields or scheduled time on the scheduled task were never being used. 

Once I fixed that most things started working as they should, I found 2 other minor things that removed any other warning messages.

I only tested it at a basic level, but I'm pretty sure that was the root issue.
I confirmed I could create an every minute cron wake up task on a group and I confirmed creating a wake up task on a group 5 minutes in the future. Both worked as expected.

Give working-1.6 a pull and let me know if that does the trick.

**Comment by swireb** [comment]
**Thank you very much for your reply. The scheduled task time is now working correctly.**

<img width="2254" height="606" alt="Image" src="https://github.com/user-attachments/assets/d6920401-3df3-4ffe-85fe-29aece1e0f34" />

**However, I found that there is still an issue when creating a scheduled task — even if I disable the wake-up option during creation, a wake-up task is still issued.**

<img width="2560" height="914" alt="Image" src="https://github.com/user-attachments/assets/5a4aa1aa-bed3-4692-b117-36b29725718d" />

**I found related logs in the log files.**
[root@localhost ~]# tail -f /opt/fog/log/fogscheduler.log
[10-11-25 10:02:09 pm] Interface Ready with IP Address: 127.0.0.1
[10-11-25 10:02:09 pm] Interface Ready with IP Address: 127.0.1.1
[10-11-25 10:02:09 pm] Interface Ready with IP Address: 172.29.200.10
[10-11-25 10:02:09 pm] Interface Ready with IP Address: localhost.localdomain
[10-11-25 10:02:09 pm]  * Starting TaskScheduler Service
[10-11-25 10:02:09 pm]  * Checking for new items every 60 seconds
[10-11-25 10:02:09 pm]  * Starting service loop
[10-11-25 10:02:09 pm]  * No tasks found!
[10-11-25 10:03:09 pm]  * No tasks found!
[10-11-25 10:04:09 pm]  * 1 task found.
[10-11-25 10:04:09 pm]  * Checking for expired checked-in tasks...
[10-11-25 10:04:09 pm]  * Scheduled Task run time: Sat, 11 Oct 2025 22:04:00 +0800
[10-11-25 10:04:09 pm]  * This is a cron style task that should run now. 
[10-11-25 10:04:09 pm]  * Found a scheduled task that should run.
[10-11-25 10:04:09 pm] 		 - Is a group based task.
[10-11-25 10:04:09 pm] 		 - Unicast task found!
[10-11-25 10:04:09 pm] 		 - Group all
[10-11-25 10:05:27 pm] 		 - Task started for group all!
[10-11-25 10:05:34 pm]  * Sending 957 wake on lan requests.
[10-11-25 10:05:34 pm]  * 957 total macs attempting to wake up.
[10-11-25 10:06:35 pm]  * 1 task found.
[10-11-25 10:06:35 pm]  * Checking for expired checked-in tasks...
[10-11-25 10:06:35 pm]  * Scheduled Task run time: Sat, 11 Oct 2025 22:06:00 +0800
[10-11-25 10:06:35 pm]  * This is a cron style task that should run now. 
[10-11-25 10:06:35 pm]  * Found a scheduled task that should run.
[10-11-25 10:06:35 pm] 		 - Is a group based task.
[10-11-25 10:06:35 pm] 		 - Unicast task found!
[10-11-25 10:06:35 pm] 		 - Group all
[10-11-25 10:08:51 pm] 		 - Task started for group all!
[10-11-25 10:08:58 pm]  * Sending 958 wake on lan requests.
[10-11-25 10:08:58 pm]  * 958 total macs attempting to wake up.
[10-11-25 10:09:58 pm]  * 1 task found.

**Comment by swireb** [comment]
**Moreover, I’m not sure whether the large number of wake-up tasks might cause the system to crash or result in very long loading times.**

<img width="2560" height="1150" alt="Image" src="https://github.com/user-attachments/assets/d3578220-12b1-424c-814d-2708ace86b80" />

**In version 1.5, I imported 1,000 computers and created 1,000 deployment tasks. Apart from the lack of pagination, there were no crashes or long loading issues. In version 1.6, I also imported 1,000 computers and created 1,000 deployment tasks, but when I refresh the page, the system crashes or takes a very long time to load.**

**Comment by darksidemilk** [comment]
We will have to generate a rather large fake import to test the freezing issue, just saying because that will take a minute to figure out, maybe Ai can generate it for me.

We will trace out where wake on Lan is being set for scheduled tasks when done from the gui, I imagine that one will be easy.

**Comment by mastacontrola** [comment]
Tracked down the remaining "wake-up still issued even when disabled" part of this.

**Root cause:** the WOL-setup block in both the host and group deploy handlers used a bare `TaskType::WAKE_UP` as the condition:

```php
if (TaskType::WAKE_UP || $wolon) {
    $wol = true;
}
```

`TaskType::WAKE_UP` is a task-type **id** constant (value `14`), not a boolean, so the condition was always true. That forced wake-on-LAN on for every task regardless of the checkbox, persisted `other4 = 1` on the scheduled task, and made the scheduler keep firing those WOL requests (the "957 wake on lan requests" you saw).

**Fix:** compare the constant against the numeric task type id, matching the existing `TaskType::WAKE_UP != $type` idiom already used a few lines up in the same handler:

```php
if (TaskType::WAKE_UP == $type || $wolon) {
    $wol = true;
}
```

Now WOL is forced only when the task itself is an actual Wake Up task; otherwise the `wol` checkbox is honored. Fixed in both `hostmanagement.page.php` and `groupmanagement.page.php`.

Committed to `working-1.6` (f73b021f1). @swireb give it a pull and confirm that scheduling a task with wake-up unchecked no longer issues WOL.

The other two open items from this thread — the slow/freezing page load with ~1000 tasks, and confirming the actual Wake Up task type still wakes hosts — are still to be looked at separately.

**Comment by mastacontrola** [comment]
Both remaining items are dealt with. Fixed in `working-1.6` (2ec3072ae).

### The slow/freezing page with ~1000 tasks

I built the fake import @darksidemilk mentioned — a container with 1000 hosts, a group containing all of them, and two snapins associated with every host — and measured instead of guessing.

Neither symptom is CPU. Both are thousands of individual round trips to MySQL, so the wall clock you see is your database's latency multiplied by a few thousand. That is also why 1.5 was fine on the same data: 1.5 does not go through the same grid machinery.

Measured on that 1000-host group, before → after:

| | queries before | queries after |
|---|---|---|
| Group deploy, all snapins (`createImagePackage`) | 5977 | **81** |
| Task list, 1000 rows (`listem('task')`) | 5004 | **1008** |
| `Group->get('hosts')` | 1011 | **3** |
| `Group->getHostCount()` | 1005 | **1** |
| `listem('host')`, 1000 ids | 1005 | **6** |

At a locally-attached DB that is 1.08s → 0.42s for the tasking and 2.24s → 1.04s for the task list. At the 15–20 ms per query a loaded or remote database gives you, ~6000 round trips is the 78 seconds in your scheduler log almost exactly.

Four causes, all on the same path:

1. **`Route::count()` was fetching every row to produce one integer.** It borrows `listem()` and then throws away everything except `recordsFiltered` — after running the full row query *and* every per-row formatter. `complex()` now takes a `$countOnly` flag and answers from the count query alone. `Group::loadHosts()` calls `getHostCount()`, so this was being paid just for touching a group.

2. **The grid formatters built one related object per row.** The host's image, a task's host, a snapin's name, a task state's icon — each one is a query, so a 1000-row grid ran ~1000 extra queries beyond its own. Ids repeat heavily down a column, so they are now resolved once per grid. The cache is emptied at the top of every `listem()` call deliberately: the services hold this class for their whole lifetime, and anything longer-lived would keep serving a renamed image or host until the daemon restarted.

3. **`HookManager::processEvent()` asked the database whether the event name was registered on every single fire.** Hooks fire constantly — `TaskState::getQueuedState()` fires one, and that sits *inside* the 1000-iteration batch loop — so a 1000-host tasking spent over 2000 round trips on it. This was the single largest contributor. The names are read once per process now; `hookEvents` is only a discovery aid for the hook debugger and the API list, and ends up with exactly the same rows.

4. **`Group::_createSnapinTasking()` queried `snapinAssoc` once per member host.** One query for the whole group now.

The task list is still 1008 queries because each of the 1000 rows names a distinct host and the tasks grid does not join `hosts`. That would need a join in the manager query; it is a separate, smaller change.

Verification: output is byte-identical before and after across all 30 API list/count endpoints, and the snapin jobs and tasks a group deploy produces fingerprint identically (same jobs, same snapins, same per-host sequence).

### Confirming the Wake Up task type still wakes hosts

It does. Running an actual Wake-Up group task against the 1000-host group:

- resolves all 1000 primary MACs,
- creates **zero** rows in `tasks` — which is correct and by design; a Wake-Up is not a task, it just sends the packets,
- and dispatches the magic-packet request to every enabled, online storage node plus the web host.

So `f73b021f1` closed the "WOL fired when unchecked" half without breaking the deliberate `$wol = true` that a real Wake-Up task still needs.

One caveat on that last point: I verified the dispatch, not the packets on the wire — the send itself is delegated to each node's `node=client&sub=wakeEmUp` endpoint, which needs real hardware to observe.

@swireb if you can pull `working-1.6` and try your 1000-host import again, I would like to know what the task list feels like now on your hardware.

**Comment by mastacontrola** [comment]
Closing — all three threads from this issue are now resolved on `working-1.6`.

1. **Scheduled tasks never appearing / wrong timing** — the `=` vs `==` `scheduleType` typo, fixed earlier.
2. **Wake-on-LAN issued even when unchecked** — `TaskType::WAKE_UP` used as a bare boolean, fixed in `f73b021f1`.
3. **Slow group tasking and the ~1000-task page freeze** — fixed in `2ec3072ae` and `5262b952f`. Roughly 6000 queries down to 81 for a 1000-host group deploy, and the 1000-row task list from 5004 queries to 9.

I also confirmed the item mastacontrola flagged as still open: an actual Wake-Up task type does still wake hosts — it resolves every member MAC, creates no `tasks` rows (correct, a Wake-Up is not a task), and dispatches to every enabled online storage node.

@swireb if you get a chance to retry your 1000-host import on `working-1.6`, please do reopen or shout if the task list still misbehaves on your hardware — my numbers are from a locally-attached database, and your original report was the thing that made the size of the problem visible. Thank you for the detail in it.

One thing found on the way out and split off rather than folded in: #956, where the server-side list layer was discarding the requested `ORDER BY`, so API pagination could repeat or skip rows. Fixed, but it was a distinct bug.
